# Image Classification using Machine learning Models

# Introduction
Image classification is a task in computer vision that involves assigning a label to an image based on its content. For example, an image classification algorithm could be used to identify the objects in an image, such as cars, people, or animals.
Computer vision is a field of artificial intelligence that deals with the extraction of meaningful information from digital images or videos. Computer vision techniques are used in a wide variety of applications, such as object detection, face recognition, and self-driving cars.

In [1]:
import os
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


# Data Gathering
Human face data is gathered from Kaggle. 

In [2]:
#an empty list to store the converted images
dataset =  []
#add path of your dataset
paths = [
    'C:/Users/DELL/Downloads/gender/dataset1/train/man',
    'C:/Users/DELL/Downloads/gender/dataset1/train/woman'
]

In [3]:

for i in paths:
    folder_name = os.path.basename(i)
    
    # Iterate over the images in the subdirectory
    for file_name in os.listdir(i):
        image_path = os.path.join(i, file_name)
        
        if os.path.isfile(image_path):  # Only consider files
            # Load the image using OpenCV
            image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
            
            # If the image was successfully loaded
            if image is not None:
                # Resize the grayscale image to 250X250 pixels
                resized_image = cv2.resize(image, (250, 250))
                
                # Flatten the image and append each pixel as a separate feature along with the label to the dataset
                flattened_image = resized_image.flatten().tolist()
                dataset.append(flattened_image + [folder_name])

# Converting image data into pixel values and a dataframe



In [4]:
# Convert the dataset to a pandas DataFrame
df = pd.DataFrame(dataset, columns=[f'pixel_{i+1}' for i in range(250*250)] + ['label'])

# Normalize the pixel values between 0 and 1
X = df.iloc[:, :-1] / 255
Y = df.iloc[:, -1]

# Encode the labels with numeric values
label_encoder = LabelEncoder()
Y_encoded = label_encoder.fit_transform(Y)
y_series = pd.Series(Y_encoded, name='Target')

# Concatenate 'X' (features) and 'y_series' (target variable) along columns (axis=1)
df_encoded = pd.concat([X, y_series], axis=1)

# Split the data into training and testing sets (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y_series, test_size=0.2, random_state=42)

In [5]:
df

pixel_1  pixel_2  pixel_3  pixel_4  pixel_5  pixel_6  pixel_7  pixel_8  \
0          63       64       65       66       68       70       71       73   
1         247      247      248      248      248      248      248      248   
2         153      153      160      169      178      177      168      160   
3          22       20       18       16       14       11       15       20   
4          82       82       81       80       78       77       73       70   
...       ...      ...      ...      ...      ...      ...      ...      ...   
1595       15       16       17       19       22       24       24       24   
1596       27       29       32       33       33       30       28       29   
1597       70       39       27       47       60       59       48       51   
1598       46       44       34       25       17       22       23       17   
1599       32       32       33       33       33       32       32       31   

      pixel_9  pixel_10  ...  pixel_62492  pixel_62493  pixel_62494  \
0          74        75  ...           19           19           19   
1         248       248  ...           32           32           31   
2         154       152  ...           21           21           20   
3          27        31  ...           33           35           35   
4          67        63  ...          157          156          156   
...       ...       ...  ...          ...          ...          ...   
1595       23        21  ...          182          180          178   
1596       31        35  ...           24           19           21   
1597       77        92  ...           99           99           99   
1598       20        40  ...            5            7            8   
1599       31        31  ...          172          175          186   

      pixel_62495  pixel_62496  pixel_62497  pixel_62498  pixel_62499  \
0              19           19           19           19           20   
1              30           30           31           33           34   
2              20           20           20           21           21   
3              36           37           37           37           37   
4             156          171          188          205          216   
...           ...          ...          ...          ...          ...   
1595          177          176          173          171          169   
1596           22           23           29           35           35   
1597           98           97           96           95           94   
1598           11           13           13            4            3   
1599          185          183          184          185          185   

      pixel_62500  label  
0              20    man  
1              36    man  
2              21    man  
3              38    man  
4             216    man  
...           ...    ...  
1595          167  woman  
1596           35  woman  
1597           94  woman  
1598            6  woman  
1599          186  woman  

[1600 rows x 62501 columns]

# Using Logistic Regression Model 

In [6]:
from sklearn.linear_model import LogisticRegression

logreg =  LogisticRegression()


In [7]:
logreg.fit(X_train, y_train)

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

# Predictions

In [8]:
y_pred = logreg.predict(X_test)

In [9]:
y_pred

array([0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,

# Accuracy Score and Confusion matrix of Linear Regression Model

In [10]:
from sklearn.metrics import accuracy_score,confusion_matrix
acc = accuracy_score(y_test, y_pred)
acc

0.828125

In [11]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[136,  35],
       [ 20, 129]], dtype=int64)

# Deploying Logistic Regression Model

In [12]:
import joblib
joblib.dump(logreg, 'clmodel.pkl')


['clmodel.pkl']

In [13]:
import cv2
import os
import numpy as np
# Load the model from the saved file
model = joblib.load('clmodel.pkl')
# Function to preprocess an input image before making predictions
def preprocess_image(image_path):
    image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    resized_image = cv2.resize(image, (250, 250))
    flattened_image = resized_image.flatten().reshape(1, -1)
    return flattened_image / 255.0

# Function to make predictions using the loaded model
def make_prediction(image_path):
    preprocessed_image = preprocess_image(image_path)
    prediction = model.predict(preprocessed_image)
    predicted_class = prediction
    return predicted_class
test_folder = "C:/Users/DELL/Downloads/gender/dataset1/test/man"  # Replace with the path to your test folder

for file_name in os.listdir(test_folder):
    image_path = os.path.join(test_folder, file_name)
    
    if os.path.isfile(image_path):  # Only consider files
        predicted_class = make_prediction(image_path)
        if predicted_class == 0:
            print(f"Image: {file_name} | Predicted Class: MAN")
        if predicted_class == 1:
            print(f"Image: {file_name} | Predicted Class: WOMAN") 

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does no

Image: face_0.jpg | Predicted Class: MAN
Image: face_1.jpg | Predicted Class: MAN
Image: face_10.jpg | Predicted Class: MAN
Image: face_101.jpg | Predicted Class: MAN
Image: face_103.jpg | Predicted Class: WOMAN
Image: face_104.jpg | Predicted Class: MAN
Image: face_105.jpg | Predicted Class: MAN
Image: face_106.jpg | Predicted Class: MAN


C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does no

Image: face_107.jpg | Predicted Class: MAN
Image: face_108.jpg | Predicted Class: MAN
Image: face_109.jpg | Predicted Class: MAN
Image: face_11.jpg | Predicted Class: WOMAN
Image: face_110.jpg | Predicted Class: MAN
Image: face_111.jpg | Predicted Class: MAN
Image: face_112.jpg | Predicted Class: MAN
Image: face_113.jpg | Predicted Class: MAN
Image: face_114.jpg | Predicted Class: MAN
Image: face_115.jpg | Predicted Class: MAN


C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does no

Image: face_116.jpg | Predicted Class: MAN
Image: face_117.jpg | Predicted Class: MAN
Image: face_118.jpg | Predicted Class: MAN
Image: face_119.jpg | Predicted Class: MAN
Image: face_12.jpg | Predicted Class: MAN
Image: face_120.jpg | Predicted Class: MAN


C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does no

Image: face_122.jpg | Predicted Class: MAN
Image: face_123.jpg | Predicted Class: WOMAN
Image: face_124.jpg | Predicted Class: MAN
Image: face_125.jpg | Predicted Class: MAN
Image: face_126.jpg | Predicted Class: MAN
Image: face_127.jpg | Predicted Class: MAN
Image: face_128.jpg | Predicted Class: MAN
Image: face_129.jpg | Predicted Class: MAN
Image: face_13.jpg | Predicted Class: MAN
Image: face_130.jpg | Predicted Class: MAN
Image: face_131.jpg | Predicted Class: MAN


C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does no

Image: face_132.jpg | Predicted Class: MAN
Image: face_133.jpg | Predicted Class: WOMAN
Image: face_134.jpg | Predicted Class: MAN
Image: face_135.jpg | Predicted Class: WOMAN
Image: face_136.jpg | Predicted Class: MAN
Image: face_137.jpg | Predicted Class: MAN
Image: face_138.jpg | Predicted Class: MAN
Image: face_139.jpg | Predicted Class: MAN
Image: face_14.jpg | Predicted Class: MAN
Image: face_140.jpg | Predicted Class: MAN
Image: face_141.jpg | Predicted Class: WOMAN


C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does no

Image: face_142.jpg | Predicted Class: MAN
Image: face_143.jpg | Predicted Class: WOMAN
Image: face_144.jpg | Predicted Class: MAN
Image: face_145.jpg | Predicted Class: MAN
Image: face_146.jpg | Predicted Class: MAN
Image: face_147.jpg | Predicted Class: MAN
Image: face_148.jpg | Predicted Class: MAN
Image: face_149.jpg | Predicted Class: MAN
Image: face_151.jpg | Predicted Class: MAN
Image: face_152.jpg | Predicted Class: MAN
Image: face_153.jpg | Predicted Class: MAN
Image: face_154.jpg | Predicted Class: WOMAN


C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does no

Image: face_156.jpg | Predicted Class: MAN
Image: face_157.jpg | Predicted Class: MAN
Image: face_158.jpg | Predicted Class: MAN
Image: face_159.jpg | Predicted Class: MAN
Image: face_16.jpg | Predicted Class: MAN
Image: face_160.jpg | Predicted Class: MAN
Image: face_161.jpg | Predicted Class: WOMAN
Image: face_162.jpg | Predicted Class: MAN


C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does no

Image: face_163.jpg | Predicted Class: MAN
Image: face_164.jpg | Predicted Class: MAN
Image: face_165.jpg | Predicted Class: MAN
Image: face_167.jpg | Predicted Class: MAN
Image: face_168.jpg | Predicted Class: WOMAN
Image: face_169.jpg | Predicted Class: MAN
Image: face_17.jpg | Predicted Class: MAN
Image: face_170.jpg | Predicted Class: MAN
Image: face_171.jpg | Predicted Class: WOMAN
Image: face_172.jpg | Predicted Class: MAN


C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does no

Image: face_173.jpg | Predicted Class: MAN
Image: face_174.jpg | Predicted Class: MAN
Image: face_175.jpg | Predicted Class: MAN
Image: face_176.jpg | Predicted Class: MAN
Image: face_177.jpg | Predicted Class: MAN
Image: face_178.jpg | Predicted Class: MAN
Image: face_179.jpg | Predicted Class: MAN
Image: face_18.jpg | Predicted Class: MAN
Image: face_180.jpg | Predicted Class: MAN
Image: face_181.jpg | Predicted Class: MAN


C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does no

Image: face_182.jpg | Predicted Class: MAN
Image: face_183.jpg | Predicted Class: MAN
Image: face_19.jpg | Predicted Class: MAN
Image: face_2.jpg | Predicted Class: MAN
Image: face_20.jpg | Predicted Class: MAN
Image: face_21.jpg | Predicted Class: MAN
Image: face_22.jpg | Predicted Class: MAN
Image: face_23.jpg | Predicted Class: MAN
Image: face_24.jpg | Predicted Class: MAN
Image: face_25.jpg | Predicted Class: MAN
Image: face_26.jpg | Predicted Class: MAN
Image: face_27.jpg | Predicted Class: MAN


C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does no

Image: face_28.jpg | Predicted Class: MAN
Image: face_29.jpg | Predicted Class: MAN
Image: face_3.jpg | Predicted Class: MAN
Image: face_30.jpg | Predicted Class: MAN
Image: face_31.jpg | Predicted Class: MAN
Image: face_32.jpg | Predicted Class: MAN
Image: face_33.jpg | Predicted Class: WOMAN
Image: face_34.jpg | Predicted Class: MAN
Image: face_35.jpg | Predicted Class: MAN
Image: face_36.jpg | Predicted Class: MAN


C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does no

Image: face_38.jpg | Predicted Class: MAN
Image: face_39.jpg | Predicted Class: MAN
Image: face_4.jpg | Predicted Class: MAN
Image: face_40.jpg | Predicted Class: MAN
Image: face_41.jpg | Predicted Class: MAN
Image: face_42.jpg | Predicted Class: WOMAN
Image: face_43.jpg | Predicted Class: MAN
Image: face_44.jpg | Predicted Class: WOMAN
Image: face_45.jpg | Predicted Class: MAN
Image: face_47.jpg | Predicted Class: MAN
Image: face_48.jpg | Predicted Class: MAN


C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does no

Image: face_49.jpg | Predicted Class: WOMAN
Image: face_5.jpg | Predicted Class: MAN
Image: face_50.jpg | Predicted Class: MAN
Image: face_51.jpg | Predicted Class: MAN
Image: face_52.jpg | Predicted Class: MAN
Image: face_53.jpg | Predicted Class: MAN
Image: face_54.jpg | Predicted Class: MAN
Image: face_55.jpg | Predicted Class: MAN
Image: face_56.jpg | Predicted Class: MAN
Image: face_57.jpg | Predicted Class: MAN
Image: face_58.jpg | Predicted Class: MAN


C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does no

Image: face_6.jpg | Predicted Class: MAN
Image: face_60.jpg | Predicted Class: MAN
Image: face_61.jpg | Predicted Class: MAN
Image: face_63.jpg | Predicted Class: MAN
Image: face_64.jpg | Predicted Class: MAN
Image: face_65.jpg | Predicted Class: MAN
Image: face_66.jpg | Predicted Class: MAN
Image: face_67.jpg | Predicted Class: MAN


C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does no

Image: face_68.jpg | Predicted Class: WOMAN
Image: face_69.jpg | Predicted Class: MAN
Image: face_7.jpg | Predicted Class: MAN
Image: face_71.jpg | Predicted Class: MAN
Image: face_72.jpg | Predicted Class: MAN
Image: face_73.jpg | Predicted Class: MAN
Image: face_74.jpg | Predicted Class: WOMAN
Image: face_75.jpg | Predicted Class: MAN
Image: face_76.jpg | Predicted Class: WOMAN
Image: face_77.jpg | Predicted Class: MAN
Image: face_78.jpg | Predicted Class: WOMAN


C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does no

Image: face_79.jpg | Predicted Class: MAN
Image: face_8.jpg | Predicted Class: MAN
Image: face_80.jpg | Predicted Class: WOMAN
Image: face_82.jpg | Predicted Class: MAN
Image: face_83.jpg | Predicted Class: MAN
Image: face_84.jpg | Predicted Class: MAN
Image: face_85.jpg | Predicted Class: WOMAN
Image: face_87.jpg | Predicted Class: MAN
Image: face_88.jpg | Predicted Class: MAN
Image: face_89.jpg | Predicted Class: MAN
Image: face_9.jpg | Predicted Class: MAN
Image: face_90.jpg | Predicted Class: MAN
Image: face_91.jpg | Predicted Class: MAN
Image: face_92.jpg | Predicted Class: MAN
Image: face_93.jpg | Predicted Class: MAN
Image: face_94.jpg | Predicted Class: WOMAN
Image: face_95.jpg | Predicted Class: MAN
Image: face_96.jpg | Predicted Class: WOMAN
Image: face_97.jpg | Predicted Class: MAN
Image: face_98.jpg | Predicted Class: MAN
Image: face_99.jpg | Predicted Class: MAN


C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does no

# Using Other Machine Learning Models

# SGDCClassifier

In [14]:
from sklearn.linear_model import SGDClassifier
from sklearn.pipeline import make_pipeline

clf = SGDClassifier(loss = 'log_loss',max_iter=1000, tol=1e-3)
clf.fit(X_train,y_train)


SGDClassifier(loss='log_loss')

In [15]:
sgdpred = clf.predict(X_test)

In [17]:
clf.densify()

SGDClassifier(loss='log_loss')

In [18]:
clf.fit(X_train, y_train, coef_init=None, intercept_init=None, sample_weight=None)

SGDClassifier(loss='log_loss')

In [19]:
clf.predict_log_proba(X_test)

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:1347: RuntimeWarning: divide by zero encountered in log
  return np.log(self.predict_proba(X))


array([[ 0.00000000e+00,            -inf],
       [ 0.00000000e+00,            -inf],
       [ 0.00000000e+00,            -inf],
       [ 0.00000000e+00,            -inf],
       [           -inf,  0.00000000e+00],
       [           -inf,  0.00000000e+00],
       [           -inf,  0.00000000e+00],
       [ 0.00000000e+00,            -inf],
       [ 0.00000000e+00,            -inf],
       [           -inf,  0.00000000e+00],
       [ 0.00000000e+00, -4.21067215e+01],
       [ 0.00000000e+00, -2.77194129e+02],
       [           -inf,  0.00000000e+00],
       [           -inf,  0.00000000e+00],
       [ 0.00000000e+00, -1.22168414e+02],
       [           -inf,  0.00000000e+00],
       [ 0.00000000e+00,            -inf],
       [           -inf,  0.00000000e+00],
       [ 0.00000000e+00,            -inf],
       [           -inf,  0.00000000e+00],
       [           -inf,  0.00000000e+00],
       [ 0.00000000e+00,            -inf],
       [ 0.00000000e+00,            -inf],
       [-1.

In [20]:
acc = accuracy_score(y_test,sgdpred)
acc

0.821875

In [21]:
cm = confusion_matrix(y_test, sgdpred)
cm

array([[156,  15],
       [ 42, 107]], dtype=int64)

# SVC (fine tuned)

In [22]:
from sklearn.svm import SVC
svcClf = SVC(kernel="sigmoid",gamma='auto', C=3,random_state = 42 )

In [23]:
svcClf.fit(X_train, y_train)

SVC(C=3, gamma='auto', kernel='sigmoid', random_state=42)

In [32]:
spred = svcClf.predict(X_test)
spred

array([0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,

# Highest Accuracy achieve

In [25]:
acc = accuracy_score(y_test,spred)
acc

0.840625

In [26]:
cm = confusion_matrix(y_test, spred)
cm

array([[140,  31],
       [ 20, 129]], dtype=int64)

In [27]:
from sklearn.ensemble import RandomForestClassifier

In [28]:
rclf = RandomForestClassifier(n_estimators=200,max_depth=3, random_state=0)
rclf.fit(X_train, y_train)

RandomForestClassifier(max_depth=3, n_estimators=200, random_state=0)

In [29]:
rpred = rclf.predict(X_test)
rpred

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,

In [30]:
acc = accuracy_score(y_test,rpred)
acc

0.75625

In [31]:
cm = confusion_matrix(y_test, rpred)
cm

array([[122,  49],
       [ 29, 120]], dtype=int64)